// ─────────────────────────────────────────────────────────────────────────────
// Customization session types
// Used by: CustomizePage, KonvaCustomizeCanvas, useCustomizationSession
// ─────────────────────────────────────────────────────────────────────────────

import type { PlacementKey, ViewName } from './garment';

/** Axis-aligned rectangle in canvas display coordinates (px) */
export interface KonvaRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

/** Konva image node attributes stored in session state */
export interface KonvaImageAttrs {
  /** Canvas X position (pixels) of the image center */
  x: number;
  /** Canvas Y position (pixels) of the image center */
  y: number;
  /** Horizontal scale factor */
  scaleX: number;
  /** Vertical scale factor */
  scaleY: number;
  /** Rotation in degrees */
  rotation: number;
}

/** State for a single garment view (front/back/left/right) */
export interface ViewState {
  /** Active placement preset key, or null if free-positioned */
  placementKey: PlacementKey | null;
  /** Design transfer width in cm (derived from placement or manual resize) */
  widthCm: number;
  /** Design transfer height in cm */
  heightCm: number;
  /** Distance from collar to top of design in cm */
  topFromCollarCm: number;
  /** Horizontal offset from garment center in cm */
  leftFromCenterCm: number;
  /** Rotation in degrees */
  rotation: number;
  /** Backend UploadAsset.id (null until design is uploaded) */
  designAssetId: string | null;
  /** Cloudinary secure_url of the uploaded design */
  designUrl: string | null;
  /** Konva node attributes for re-hydrating canvas on view switch */
  konvaNodeAttrs: KonvaImageAttrs | null;
  /** True if the design bounding box extends outside the safe frame */
  isOutsideSafeArea: boolean;
  /** Base64 data URL generated by Stage.toDataURL() for this view (for preview/thumbnail) */
  previewDataUrl: string | null;
}

/** Full customization session — persisted to localStorage as draft */
export interface CustomizationSession {
  productSlug: string;
  /** ProductVariant.id */
  variantId: string;
  /** Garment size (e.g. "M", "L", "Youth M") */
  size: string;
  /** Variant color name (e.g. "White", "Black") */
  color: string;
  quantity: number;
  /** Per-view state */
  views: Partial<Record<ViewName, ViewState>>;
  /** Currently displayed view */
  activeView: ViewName;
  /** ISO string or null if not yet saved to backend */
  savedAt: string | null;
  /** Backend customization record ID (set after successful save) */
  customizationId: string | null;
}

/** Summary of one view's placement — used in cart optionPayload */
export interface PlacementSummaryItem {
  view: ViewName;
  placementKey: PlacementKey | null;
  widthCm: number;
  heightCm: number;
  rotation: number;
  designAssetId: string | null;
}

/**
 * Payload stored in CartItem.optionPayload.customization
 * Attached when user adds a customized item to cart.
 */
export interface CartCustomizationPayload {
  customizationId: string;
  previewUrl: string;
  placementSummary: PlacementSummaryItem[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Factory helpers
// ─────────────────────────────────────────────────────────────────────────────

export function createEmptyViewState(): ViewState {
  return {
    placementKey: null,
    widthCm: 0,
    heightCm: 0,
    topFromCollarCm: 0,
    leftFromCenterCm: 0,
    rotation: 0,
    designAssetId: null,
    designUrl: null,
    konvaNodeAttrs: null,
    isOutsideSafeArea: false,
    previewDataUrl: null,
  };
}

export function createEmptySession(
  productSlug: string,
  variantId: string,
  size: string,
  color: string,
  quantity: number,
  initialView: ViewName = 'front'
): CustomizationSession {
  return {
    productSlug,
    variantId,
    size,
    color,
    quantity,
    views: {
      [initialView]: createEmptyViewState(),
    },
    activeView: initialView,
    savedAt: null,
    customizationId: null,
  };
}
